# Generated by Django 5.1.6 on 2025-03-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_barcode_alter_item_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
