# Generated by Django 5.1.6 on 2025-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='12312312', editable=False, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
